### ISSUE TITLE
Ensure emails aren't classified as spam

### ISSUE THREAD

**Issue by nosajio** [wemakehq/email-handler#1]
Not necessarily a code related change, as the first thing we should do is validate the domain name in sendgrid, and send using wemakehq.com.

**Comment by likewerealive** [comment]
<img width="384" alt="Screenshot 2019-11-06 at 20 31 17" src="https://user-images.githubusercontent.com/881374/68335483-71c4a180-00d4-11ea-8a63-381e52c96b9d.png">

All sorted @nosajio :)
